### ISSUE TITLE
Add debounce to Controls class.

### ISSUE THREAD

**Issue by nbgray** [PearceRobotics/infinite-recharge-2020#24]
Add debounce to all buttons in Controls class.

**Comment by kushagharahi** [comment]
What do you think about command based programming? 
https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html

If we follow the command based programming paradigm a de-bounce isn't really needed since they take care of that stuff for you: https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html

**Comment by kushagharahi** [comment]
@nbgray What do you think about command based programming?
https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html

If we follow the command based programming paradigm a de-bounce isn't really needed since they take care of that stuff for you: https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html

**Comment by nbgray** [comment]
If you want to go with triggers we can, but it means they don't get to learn what a debounce is and why you'd want it.  I guess I'm just old school (literally programmed the robot before some of these students were born) and I want them to implement most of the control algorithms manually.

**Comment by Stuart1745** [comment]
so the elite controllers have internal debouncing.  its not really a thing anymore if we do want to talk about it we should do it as a lesson as they won't really see it in practice

**Comment by nbgray** [comment]
Closing the issue since we're going with command based programming.
